export const LOAD_DATA = 'order/load_data'
export const GET_DIR = 'order/get_dir'
export const SAGA_LOAD_DATA ='order/saga_load_data'
export const LOAD_MORE_DATA = 'order/load_more_data'
export const SAGA_LOAD_MORE_DATA = 'order/saga_load_more_data'